---

- hosts: all # all hosts, in this case just the server
  vars_files: ../vars.yml
  become: yes # i.e. become sudo

  tasks:
    - include_tasks: update_system.yml
    - include_tasks: install_docker.yml
    - include_tasks: create_docker_network.yml

    - name: Create services group
      group:
        name: "{{ services_name }}"
        state: present
        gid: "{{ services_gid }}"

      #- include_tasks: nginx.yml
    - include_tasks: unbound.yml
    - include_tasks: pihole.yml
    - include_tasks: swag.yml
    - include_tasks: wireguard.yml
    - include_tasks: deluge.yml
      #- include_tasks: jackett.yml
    - include_tasks: prowlarr.yml
    - include_tasks: readarr.yml
    - include_tasks: foundry.yml
